name: Disk Layout CI

on: [push, pull_request]

env:
  NIX_CONFIG: "experimental-features = nix-command flakes"

jobs:
  vm-tests:
    name: NixOS VM tests
    runs-on: native
    steps:
      - uses: actions/checkout@v4

      - name: Run NixOS disko VM tests
        run: |
          nixpkgs=$(nix eval --raw --impure \
            "(builtins.getFlake \"path:$(pwd)/test-config\").inputs.nixpkgs.outPath")
          NIX_PATH="nixpkgs=${nixpkgs}" \
          nix flake check ./test-config \
            --option extra-system-features "nixos-test kvm benchmark big-parallel" \
            --keep-going \
            --impure
