pub const APP_ID: &str = "org.xinux.Xeonitte";
pub const GETTEXT_PACKAGE: &str = "xeonitte";
pub const LOCALEDIR: &str = concat!(/* RESULT_PATH */ "/usr/local/share/locale");
pub const PKGDATADIR: &str = concat!(/* RESULT_PATH */ "/usr/local/share/xeonitte");
pub const SYSCONFDIR: &str = "/etc";
pub const LIBEXECDIR: &str = concat!(/* RESULT_PATH */ "/usr/local/libexec");
pub const PROFILE: &str = "";
pub const RESOURCES_FILE: &str = concat!(/* RESULT_PATH */ "/usr/local/share/xeonitte", "/resources.gresource");
pub const VERSION: &str = "0.0.1";
