install_data('config.yml', install_dir : pkgconfdir / 'xeonitte')

install_subdir('init', install_dir : pkgconfdir / 'xeonitte')
install_subdir('basic', install_dir : pkgconfdir / 'xeonitte')
install_subdir('advanced', install_dir : pkgconfdir / 'xeonitte')

install_subdir('configcopy', install_dir : pkgconfdir / 'xeonitte')
install_subdir('relago', install_dir : pkgconfdir / 'xeonitte')


subdir('branding/xinux')
