[options]
work_mode = "sys"
library = "Vte"
version = "3.91"
min_cfg_version = "0.68"
single_version_file = "."
girs_directories = ["../../gir-files", "../../"]

external_libraries = [
    "GLib",
    "Gio",
    "Pango",
]

[external_libraries]
gdk4="Gdk"
gtk4="Gtk"
